### ISSUE TITLE
Call to undefined method `PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getRequireExtendsTagValues()`

### ISSUE THREAD

**Issue by AcostaLm** [rectorphp/rector#8419]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.13             |
| PHPStan version | 1.10.56             |

After upgrading PHPStan from version 1.10.54 to 1.10.56, I am unable to run Rector in my project. I consistently receive the following error message for any PHP file.

`vendor/bin/rector process`:
```
[ERROR] Could not process "app/Services/UserPreferenceService.php" file, due to:
         "Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getRequireExtendsTagValues()". On line:
         328
```

`vendor/bin/rector process -vvv`:
```
[ERROR] Could not process "/var/www/html/hotel/app/Services/UserPreferenceService.php" file, due to:
         "System error: "Call to undefined method
         PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getRequireExtendsTagValues()"

         Stack trace:
         #0 phar://vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/ResolvedPhpDocBlock.php(503):
         PHPStan\PhpDoc\PhpDocNodeResolver->resolveRequireExtendsTags()
         #1 phar://vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/ResolvedPhpDocBlock.php(258):
         PHPStan\PhpDoc\ResolvedPhpDocBlock->getRequireExtendsTags()
         #2 phar://vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanceResolver.php(56):
         PHPStan\PhpDoc\ResolvedPhpDocBlock->merge()
         #3 phar://vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanceResolver.php(42):
         PHPStan\PhpDoc\PhpDocInheritanceResolver->docBlockTreeToResolvedDocBlock()
         #4 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3743):
         PHPStan\PhpDoc\PhpDocInheritanceResolver->resolvePhpDocForMethod()
         #5 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(527):
         PHPStan\Analyser\NodeScopeResolver->getPhpDocs()
         #6 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(401):
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()
         #7 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(668):
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
         #8 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(401):
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()
         #9 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(640):
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
         #10 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(370):
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()
         #11 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(211):
         PHPStan\Analyser\NodeScopeResolver->processNodes()
         #12 vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(53):
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes()
         #13 vendor/rector/rector/src/Application/FileProcessor.php(200):
         Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile()
         #14 vendor/rector/rector/src/Application/FileProcessor.php(146):
         Rector\Core\Application\FileProcessor->parseFileNodes()
         #15 vendor/rector/rector/src/Application/FileProcessor.php(105):
         Rector\Core\Application\FileProcessor->parseFileAndDecorateNodes()
         #16 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):
         Rector\Core\Application\FileProcessor->processFile()
         #17 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):
         Rector\Core\Application\ApplicationFileProcessor->processFile()
         #18 vendor/rector/rector/src/Console/Command/WorkerCommand.php(132):
         Rector\Core\Application\ApplicationFileProcessor->processFiles()
         #19 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}()
         #20 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202312\Evenement\EventEmitter->emit()
         #21 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202312\Clue\React\NDJson\Decoder->handleData()
         #22 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202312\Evenement\EventEmitter->emit()
         #23 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202312\React\Stream\Util::RectorPrefix202312\React\Stream\{closure}()
         #24 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202312\Evenement\EventEmitter->emit()
         #25 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202312\React\Stream\DuplexResourceStream->handleData()
         #26 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202312\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #27 vendor/rector/rector/src/Console/Command/WorkerCommand.php(90):
         RectorPrefix202312\React\EventLoop\StreamSelectLoop->run()
         #28 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):
         Rector\Core\Console\Command\WorkerCommand->execute()
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(960):
         RectorPrefix202312\Symfony\Component\Console\Command\Command->run()
         #30 vendor/rector/rector/vendor/symfony/console/Application.php(333):
         RectorPrefix202312\Symfony\Component\Console\Application->doRunCommand()
         #31 vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202312\Symfony\Component\Console\Application->doRun()
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(216):
         Rector\Core\Console\ConsoleApplication->doRun()
         #33 vendor/rector/rector/bin/rector.php(129): RectorPrefix202312\Symfony\Component\Console\Application->run()
         #34 vendor/rector/rector/bin/rector(5): require_once('...')
         #35 vendor/bin/rector(119): include('...')
         #36 {main}". On line: 328
```

If I change the PHPStan version using the command `composer require --dev phpstan/phpstan:1.10.54`, then Rector works as expected.

Because PHPStan version 1.10.55 introduced changes related to @phpstan-require-extends, as mentioned in the [release notes](https://github.com/phpstan/phpstan/releases/tag/1.10.55), it might be the reason why Rector is not working properly with PHPStan version 1.10.56.
## Minimal PHP Code Causing Issue

Any PHP file.

**Comment by samsonasik** [comment]
That resolved in 0.19. You can update your composer.json to : `"rector/rector": ^0.19.2"` and run composer update.

**Comment by AcostaLm** [comment]
Sorry for my mistake. 

I had a previous version of "rector/rector": "^0.18.12" blocked in my composer.json file.

Thank you very much, great work!!
