### ISSUE TITLE
Undefined method `Rector\Config\RectorConfig::tag()` when upgrading from `2.6.3` to `2.6.4`

### ISSUE THREAD

**Issue by u01jmg3** [rectorphp/rector#9880]
# Bug Report

| Subject        | Details |
| :------------- | :------ |
| Rector version | 2.6.4  |

## Minimal PHP Code Causing Issue

The project does not explicitly call `RectorConfig::tag()`.

The error occurs when upgrading `rector/rector` from `2.6.3` to `2.6.4`:

```text
Call to undefined method Rector\Config\RectorConfig::tag()
```

The same configuration works correctly with Rector `2.6.3`.

## Expected Behaviour

Rector `2.6.4` should process the existing configuration without attempting to call the undefined `RectorConfig::tag()` method.

The project does not directly use `RectorConfig::tag()`, so the call appears to originate from Rector itself or from one of the configured rules/sets.

<details>
<summary><b>Rector Config</b></summary>

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;
use Rector\ValueObject\PhpVersion;
use RectorLaravel\Set\LaravelSetList;

return RectorConfig::configure()
    ->withParallel(120 * 2, 16, 16)
    ->withPhpVersion(PhpVersion::PHP_74)
    ->withSets([
        LaravelSetList::LARAVEL_50,
        LaravelSetList::LARAVEL_51,
        LaravelSetList::LARAVEL_52,
        LaravelSetList::LARAVEL_53,
        LaravelSetList::LARAVEL_54,
        SetList::CODE_QUALITY,
        SetList::CODING_STYLE,
        SetList::DEAD_CODE,
        SetList::PHP_70,
        SetList::PHP_71,
        SetList::PHP_72,
        SetList::PHP_73,
        SetList::PHP_74,
    ])
    ->withPaths([
        __DIR__ . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'Console',
        __DIR__ . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'Models',
        __DIR__ . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'Providers',
        __DIR__ . DIRECTORY_SEPARATOR . 'config',
        __DIR__ . DIRECTORY_SEPARATOR . 'tests',
    ])
    ->withSkip([
        // Files
        __DIR__ . DIRECTORY_SEPARATOR . 'app/Console/Kernel.php',
        // Rectors
        Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector::class,
        Rector\CodeQuality\Rector\FuncCall\ChangeArrayPushToArrayAssignRector::class,
        Rector\CodeQuality\Rector\FuncCall\CompactToVariablesRector::class,
        Rector\CodeQuality\Rector\Identical\BooleanNotIdenticalToNotIdenticalRector::class,
        Rector\CodeQuality\Rector\Identical\SimplifyBoolIdenticalTrueRector::class,
        Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector::class,
        Rector\CodeQuality\Rector\Isset_\IssetOnPropertyObjectToPropertyExistsRector::class,
        Rector\CodeQuality\Rector\FunctionLike\SimplifyUselessVariableRector::class,
        Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector::class,
        Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector::class,
        Rector\Php71\Rector\TryCatch\MultiExceptionCatchRector::class,
        Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector::class,
        Rector\DeadCode\Rector\ClassMethod\RemoveUselessParamTagRector::class,
        Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPromotedPropertyRector::class,
        Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector::class,
        Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector::class,
        Rector\Transform\Rector\String_\StringToClassConstantRector::class,
        Rector\CodeQuality\Rector\FuncCall\InlineIsAInstanceOfRector::class,
        Rector\DeadCode\Rector\ClassMethod\RemoveUselessReturnTagRector::class,
        Rector\CodingStyle\Rector\ClassLike\NewlineBetweenClassLikeStmtsRector::class,
        Rector\TypeDeclaration\Rector\StmtsAwareInterface\SafeDeclareStrictTypesRector::class,
    ]);
```
</details>

**Comment by TomasVotruba** [comment]
What your Laravel Rector version?
Try the latest tag: https://github.com/driftingly/rector-laravel/releases Should be fixed there.

**Comment by u01jmg3** [comment]
We can't use `rector-laravel` because it requires PHP 8.3, and unfortunately, we're still supporting a legacy app running PHP 7.4.

**Comment by TomasVotruba** [comment]
Rector 2.6 changed the way it loads sets and container package and is not compatible with older rector-laravel version. 
This is chicken-egg issue. 

Either you cannot use legacy rector-laravel or bump Rector itself. I recommend bumping PHP to higher version, 7.4 is way too dangerous to use.

**Comment by u01jmg3** [comment]
- Was it intentional to add this breaking change to a patch version of Rector? I didn't see anywhere that Rector Laravel would stop working unless you are using [driftingly/rector-laravel](https://github.com/driftingly/rector-laravel).

To confirm, I must remove:

```diff
withSets([
-        LaravelSetList::LARAVEL_50,
-        LaravelSetList::LARAVEL_51,
-        LaravelSetList::LARAVEL_52,
-        LaravelSetList::LARAVEL_53,
-        LaravelSetList::LARAVEL_54,
])
```

---

> _I recommend bumping PHP to higher version, 7.4 is way too dangerous to use._

I agree, but in some industries, things move much slower, and I'm not in a position to influence that.

**Comment by TomasVotruba** [comment]
Yes, set lists are deprecated for a long long time (E.g. here in Symfony https://github.com/rectorphp/rector-symfony/pull/912/
) and `withComposerBased(...)` should be used instead:
https://getrector.com/documentation/composer-based-sets

Set lists by themselves required daunting adding of new linew on every new framework release. Sometimes creating conflicting situations, as what worked in v5, was gone in v6, and sometimes returned in v9 (e.g. PHPUnit).

Once you upgrade PHP version, use `->withComposerBased(laravel: true)` instead to autoamte the process.


I'm thinking, maybe we could find a way to include Laravel Rector in the build here, so everyone gets downgrade version 🤔

**Comment by u01jmg3** [comment]
I realise there comes a point where you need to modernise and can no longer continue supporting old PHP, but Rector does say it supports PHP 7.4 according to Composer. 🤷🏻‍♂️

It's just that my build was 🟢, then Dependabot suggested bumping Rector to `2.6.4`, and what was previously passing started to fail. If there's a fix, that would be great. 👍🏻

**Comment by TomasVotruba** [comment]
This should fix your issue and won't crash: https://github.com/rectorphp/rector-src/pull/8431
But make sure to upgrade to latest Laravel Rector, otherwise you're missing lot of features added recently.
